Pages/Account/Edit.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web2.Models;

namespace Web2.Pages
{
    public class EditModel : PageModel
    {
		private readonly Web2.Data.AppDbContext _context;
		UserManager<User> _userManager;
		public EditModel(Web2.Data.AppDbContext context, UserManager<User> userManager)
		{
			_context = context;
			_userManager = userManager;
        }			

		[BindProperty]
		public User user { get; set; }
        // получение данных пользователя
        public async Task<IActionResult> OnGetAsync(string id)
		{
			if (id == null)
			{
				return NotFound();
			}
            user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
			return Page();
		}
        // изменение данных пользователя
        public async Task<IActionResult> OnPostEditAsync(IList<string> UserRoles)
        {
            var user2 = await _userManager.FindByIdAsync(user.Id);

            if (user != null)
            {
                user2.Name = user.Name;
                user2.Surname = user.Surname;
                user2.Phone = user.Phone;
            }

            IdentityResult result = await _userManager.UpdateAsync(user2);

            if (result.Succeeded)
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect("/Account/Log");
            }
            else
            {
                ModelState.AddModelError("", "Что-то пошло не так");
            }
            return Page();
        }

        private bool UserExists(string id)
        {
            return _context.user.Any(e => user.Id == id);
        }
    }
}

Pages/Account/ForgotPassword.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web2.Models;

namespace Web2.Pages
{
    public class ForgotPasswordModel : PageModel
    {
        public UserManager<User> _userManager;
        public ForgotPasswordModel(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        // отправка сообщения о сбросе пароля
        public async Task<IActionResult> OnPostForgotPassword(string Email)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Email);
                if (user == null || !await _userManager.IsEmailConfirmedAsync(user))
                {
                    ModelState.AddModelError("", "Email не найден");
                    return Page();
                }

                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                var callbackUrl = Url.Page(
                        "/Account/ResetPassword",
                        null,
                    new { userId = user.Id, code },
                    protocol: HttpContext.Request.Scheme);
                EmailService emailService = new EmailService();
                await emailService.SendEmailAsync(Email, "Сброс пароля",
                    $"Для сброса пароля пройдите по ссылке: <a href='{callbackUrl}'>link</a>");
            }
            return RedirectToPage("/Account/ForgotPasswordConfirmation");
        }
    }
}

Pages/Account/ForgotPasswordConfirmation.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web2.Pages
{
    public class ForgotPasswordConfirmationModel : PageModel
    {
        public void OnGet(){}
    }
}

Pages/Account/Log.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web2.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace Web2.Pages
{
    public class LogModel : PageModel
    {
        private readonly Web2.Data.AppDbContext _context;
        private readonly SignInManager<User> _signInManager;
        private readonly ILogger<LoginModel> _logger;
        public UserManager<User> _userManager;
        public LogModel(Web2.Data.AppDbContext context, UserManager<User> userManager, SignInManager<User> signInManager, ILogger<LoginModel> logger)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public IList<User> user { get; set; } = default!;
	[BindProperty]
	public LogMod mod { get; set; }
        public IList<AuthenticationScheme> ExternalLogins { get; set; }
        public string ReturnUrl { get; set; }
        [TempData]
        public string ErrorMessage { get; set; }
        // класс для авторизации пользователя
        public class LogMod
        {
            [Required]
            [EmailAddress]
            public string? Email { get; set; }

            [Required]
	    public string? Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }
        // авторизация
        public async Task<IActionResult> OnPostLogin(LogMod mod)
        {
            mod.Email = mod.Email.ToLower();
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            if (ModelState.IsValid)
            {
                var user = await _signInManager.PasswordSignInAsync(mod.Email, mod.Password, mod.RememberMe, lockoutOnFailure: false);
                if (user.Succeeded)
                {
                    await Authenticate(mod.Email); // аутентификация

                    _logger.LogInformation("User logged in.");

		    return RedirectToPage("./Log");
                }
                ModelState.AddModelError("", "Неверный логин или пароль");
            }
            return Page();
        }
        // аутентификация
        private async Task Authenticate(string userName)
        {
            var user = await _userManager.FindByNameAsync(userName);
            var Role= await _userManager.GetRolesAsync(user);
            // создаем один claim
            var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, userName),
                new Claim(ClaimsIdentity.DefaultRoleClaimType, Role[0])
            };
            // создаем объект ClaimsIdentity
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            // установка аутентификационных куки
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }
        // выход пользователя
		public async Task<IActionResult> OnPostLogout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

			await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);

			return RedirectToPage("./Log");
        }
        // получение данных пользователя
        public async Task OnGetAsync()
		{
            if (User.Identity.IsAuthenticated)
            {
                string Log = User.Identity.Name.ToString();
                if (_context.user != null)
                {
                    user = await _context.user.FromSqlRaw($"SELECT * FROM \"AspNetUsers\" WHERE \"UserName\"=\'{Log}\'").ToListAsync();
                }
            }
		}
	}
}

Pages/Account/ResetPassword.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Web2.Models;

namespace Web2.Pages
{
    public class ResetPasswordModel : PageModel
    {
        public UserManager<User> _userManager;
        public ResetPasswordModel(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        // класс для сброса пароля
        public class ResetPasswordMod
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "Пароль должен содержать как минимум 6 символов", MinimumLength = 6)]
            public string Password { get; set; }

            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "Пароли не совпадают")]
            public string ConfirmPassword { get; set; }

            public string Code { get; set; }
        }
        [BindProperty]
        public ResetPasswordMod mod { get; set; }
        // вызов ошибки при несанкционированном доступе
        public IActionResult OnGet(string code)
        {
            mod = new ResetPasswordMod { Code = code };
            return code == null ? Redirect("./Error") : Page();
        }
        // сброс пароля
        public async Task<IActionResult> OnPostResetPassword(ResetPasswordMod model)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var user = await _userManager.FindByEmailAsync(model.Email);
            if (user == null)
            {
                return Redirect("/Account/ResetPasswordConfirmation");
            }
            var result = await _userManager.ResetPasswordAsync(user, model.Code, model.Password);
            if (result.Succeeded)
            {
                return Redirect("/Account/ResetPasswordConfirmation");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return Page();
        }
    }
}

Pages/Account/ResetPasswordConfirmation.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web2.Pages
{
    public class ResetPasswordConfirmationModel : PageModel
    {
        public void OnGet(){}
    }
}

Pages/Admin/Edit.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web2.Models;

namespace Web2.Pages.Admin
{
    public class EditModel : PageModel
    {
	private readonly Web2.Data.AppDbContext _context;
	UserManager<User> _userManager;
        // выбор роли пользователя
	public List<SelectListItem>? GetRole()
	{
	    List<SelectListItem> role = new List<SelectListItem>();
	    role.Add(new SelectListItem() { Text = "Доктор", Value = "Doctor" });
	    role.Add(new SelectListItem() { Text = "Админ", Value = "Admin" });
	    return role;
	}
	public EditModel(Web2.Data.AppDbContext context, UserManager<User> userManager)
	{
	    _context = context;
	    _userManager = userManager;
        }			
	[BindProperty]
	public User user { get; set; }
        public IList<string> UserRoles { get; set; }
        // получение данных пользователя
        public async Task<IActionResult> OnGetAsync(string id)
	{
	    if (id == null)
	    {
		return NotFound();
	    }
            user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            UserRoles = await _userManager.GetRolesAsync(user);
	    return Page();
	}
        // изменение данных пользователя
        public async Task<IActionResult> OnPostEditAsync(IList<string> UserRoles)
        {
            var user2 = await _userManager.FindByIdAsync(user.Id);
            var userRoles = await _userManager.GetRolesAsync(user);
            var addedRoles = UserRoles.Except(userRoles);
            var removedRoles = userRoles.Except(UserRoles);

            await _userManager.AddToRolesAsync(user, addedRoles);

            await _userManager.RemoveFromRolesAsync(user, removedRoles);

            if (user != null)
            {
                user2.Name = user.Name;
                user2.Surname = user.Surname;
                user2.Email = user.Email;
                user2.Phone = user.Phone;
            }

            IdentityResult result = await _userManager.UpdateAsync(user2);

            if (result.Succeeded)
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect("/Admin/AdminPanel");
            }
            else
            {
                ModelState.AddModelError("", "Что-то пошло не так");
            }
            return Page();
        }

        private bool UserExists(string id)
        {
            return _context.user.Any(e => user.Id == id);
        }
    }
}

Pages/Database/Analyzes/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web2.Models;

namespace Web2.Pages.Database.Analyzes
{
    public class EditModel : PageModel
    {
        private readonly Web2.Data.AppDbContext _context;

        public EditModel(Web2.Data.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Analyzes Analyzes { get; set; }
        [BindProperty]
        public patient_archive Patient { get; set; }
        [BindProperty]
        public Patient_Analyzes P_A { get; set; }
        // получение анализов пациентов
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Analyzes = await _context.analyzes.FirstOrDefaultAsync(m => m.id_analysis == id);
            P_A = await _context.patient_analyzes.FirstOrDefaultAsync(m => m.id_analysis == id);

            if (Analyzes == null)
            {
                return NotFound();
            }
            return Page();
        }
        // изменение анализов пациентов
        public async Task<IActionResult> OnPostEditAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var id_a = await _context.patient_analyzes.FromSqlRaw($"SELECT * FROM patient_analyzes WHERE id_analysis={Analyzes.id_analysis}").ToListAsync();
            var b = await _context.patient_analyzes.FindAsync(id_a[0].id_patient, Analyzes.id_analysis);
            if (b != null)
            {
                _context.patient_analyzes.Remove(b);
                await _context.SaveChangesAsync();
            }

            P_A.analyzes = Analyzes;
            _context.Attach(Analyzes).State = EntityState.Modified;
            _context.patient_analyzes.Add(P_A);

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PatientExists(Analyzes.id_analysis))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Analyzes");
        }

        private bool PatientExists(int id)
        {
            return _context.analyzes.Any(e => e.id_analysis == id);
        }
    }
}

Pages/Account/Edit.cshtml
@page
@model Web2.Pages.EditModel
@{
    Layout = null;
}
@{
    ViewData["Title"] = "Edit";
}

<body>

    <h1>Редактирование</h1>

    <h4>Личные данные</h4>
    <hr />

    <div class="row">
        <div class="col-md-7">
            <form asp-page-handler="edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="user.Id" />
                <div class="form-group">
                    <label>Имя</label>
                    <input asp-for="user.Name" class="form-control" />
                    <span asp-validation-for="user.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label>Фамилия</label>
                    <input asp-for="user.Surname" class="form-control" />
                    <span asp-validation-for="user.Surname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label>Номер телефона</label>
                    <input type="tel" asp-for="user.Phone" class="form-control" />
                    <span asp-validation-for="user.Phone" class="text-danger"></span>
                </div>
                <p>
                    <div class="form-group">
                        <input type="submit" value="Сохранить" class="btn btn-primary" />
                    </div>
                </p>
            </form>
        </div>
    </div>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

</body>

Pages/Account/ForgotPassword.cshtml
@page
@model Web2.Pages.ForgotPasswordModel
@{
    ViewData["Title"] = "Забыли пароль?";
}

@{
    if (ViewData["Message"] != null)
    {
        <div>
            @ViewData["Message"]
        </div>
    }
}

<head>
    <link rel="stylesheet" href="~/css/Windows.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/modal.css" asp-append-version="true" />
</head>


<body>

    <div class="parent">
        <div class="auth_dialog_header">
            <span class="auth_dialog_title">
                <span class="auth_dialog_title_second">
                    Личный кабинет
                </span>
                <span class="auth_dialog_title_third">
                    сотрудника
                </span>
            </span>
        </div>
    <div class="block">
    <form asp-page-handler="ForgotPassword" method="post" class="form-horizontal">
                <fieldset class="fieldsetA">
                    <h2>@ViewData["Title"]</h2>
                    <legend class="legentA">Введите email</legend>
    <div asp-validation-summary="All" class="text-danger"></div>
        <div>
        <label name="Email" class="col-md-2 control-label"></label>
            <div style="padding: 2px;" class="divA">
            <input name="Email" class="inputA" />
        </div>

            <div style="padding: 5px;" class="col-md-offset-2 divA">
            <button type="submit" class="inputA c-button">Отправить</button>
        </div>
    </div>

                </fieldset>
            </form>
</div>
</div>
</body>

Pages/Account/ForgotPasswordConfirmation.cshtml
@page
@model Web2.Pages.ForgotPasswordConfirmationModel
@{
    ViewData["Title"] = "Сбросить пароль";
}

<h2>@ViewData["Title"]</h2>
<p>
    Для сброса пароля перейдите по ссылке в письме, отправленном на ваш email.
</p>


Pages/Account/Log.cshtml
@page
@model Web2.Pages.LogModel
@{
	@if (!User.Identity.IsAuthenticated)
	{
		ViewData["Title"] = "Вход в личный кабинет";
	}
	else
	{
		ViewData["Title"] = "Личный кабинет";
	}
}
@{
	if (ViewData["Message"] != null)
	{
		<div>
			@ViewData["Message"]
		</div>
	}
}

<head>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
</head>

<body>

	@if (!User.Identity.IsAuthenticated){
		<div data-aos="fade-up-left" class="parent">

			<div class="auth_dialog_header">
				<span class="auth_dialog_title">
					<span class="auth_dialog_title_second">
						Личный кабинет
					</span>
					<span class="auth_dialog_title_third">
						сотрудника
					</span>
				</span>
			</div>

			<div class="block">
				<form asp-page-handler="Login" method="post">
					<fieldset class="fieldsetA"> 

					<legend class="legentA">Вход в личный кабинет</legend> 
					<div class="divA"> 
						<label for="siteLogin" class="labelLogin">Логин</label>
						<input name="email" asp-for="mod.Email" class="inputA" value="" id="siteLogin" type="text" />
						<span asp-validation-for="mod.Email" class="text-danger"></span>
					</div>

					<div class="divA">
						<label for="sitePass" class="labelLogin">Пароль</label>
						<input name="password" asp-for="mod.Password" class="inputA" value="" id="sitePass" type="password" />
						<i class="password-control fas fa-eye"></i>
						<span asp-validation-for="mod.Password" class="text-danger"></span>
					</div>

					<div style="width: 355px;" asp-validation-summary="ModelOnly" class="text-danger"></div>

					<div class="divA">
						<input type="checkbox" name="rememberme" value="True"/>
						<span>запомнить меня</span>
					</div>

					<div class="divA">
						<input value="Войти" style="width: 150px" class="inputA c-button" type="submit" />
					</div>
			
					<div>
						<p><a href="/Account/ForgotPassword">Забыли пароль?</a></p>
					</div>

					</fieldset> 
				</form>
			</div>
		</div>
	}
	else
	{
		<div data-aos="fade-up-left">

			<div class="table-responsive">

				<div style="display: flex; flex-wrap: nowrap; justify-content: flex-start; align-items: center; margin: 0px 0px 10px 0px;">

					<h2> Мой профиль |</h2>

					@foreach (var item in Model.user)
					{
						<div>
							<a class="bt-ur3" style="font-size: 1.25rem;" title="Настройки" onclick="openModal({ url: '/Account/Edit', data: '@item.Id' })"
								datd-toggle="ajax-modal" data-target="Modal">
							<i class="fas fa-cog"></i>
							</a>
						</div>
					}

				</div>

				<div style="display: flex; flex-wrap: wrap; justify-content: space-between;">

					<div style="background: #039383 !important; padding: 20px; border: 1px solid #dcdcff; border-radius: 20px;">

						<div class="all_windows" style="padding: 20px; margin: 0px 0px 50px 0px;">

							<table id="tblCustomers" class="table table-hover">
							@foreach (var item in Model.user)
							{
								<tr>
								<td>
									Имя
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Name)
								</td>
								</tr>
								<tr>
								<td>
									Фамилия
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Surname)
								</td>
								</tr>
								<tr>
								<td>
									Email
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Email)
								</td>
								</tr>
								<tr>
								<td>
									Телефон
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Phone)
								</td>
								</tr>
							}
							</table>
						</div>

						<div class="all_windows">

							@if (User.IsInRole("Doctor"))
							{
								<div>
									<h7>
										Подключенные функции |  🟢Доктора
									</h7>
								</div>

								<div style="padding:10px">
									<button class="c-button" onclick="document.location='/Database/Patients/Patients'">Пациенты</button>
								</div>
							}
							@if (User.IsInRole("Admin"))
							{
								<div>
									<h7>
										Подключенные функции |  🟢Админа
									</h7>
								</div>

								<div style="padding:10px">
									<button class="c-button" onclick="document.location='/Admin/AdminPanel'">Панель администратора</button>
								</div>
							}

							<div style="padding:10px">
								<form asp-page-handler="Logout" method="post">
									<input value="Выйти" class="inputA c-button" type="submit" />
								</form>
							</div>

						</div>

					</div>

					<div class="calendar-wrapper">
						<button id="btnPrev" type="button">Предыдущий</button>
						<button id="btnNext" type="button">Следующий</button>
						<div id="divCal"></div>
					</div>

				</div>

			
			</div>
		</div>
	}

 @section scripts{

    <script src="~/scripts/log.js" asp-append-version="true"></script>

	<partial name="_ValidationScriptsPartial" />
	<script>
		$(document).ready(function(){ 
			if($("#siteLogin").val()!='') 
			{ 
				$("#siteLogin").prev().text(''); 
				$("#sitePass").prev().text(''); 
			} 
			/*связь события и получение полем фокуса*/ 
			$("div > input").focus( 
				function(e) 
				{ 
					var clicked = $(e.target), 
					clickedId = clicked.attr("id"); 
			/* удаление текста из label при получении фокуса для поля логина*/ 
			if(clickedId=="siteLogin") 
			{ 
				clicked.prev().text(''); 
			} /*тоже самое для пароля*/ 
			else if(clickedId=="sitePass") 
			{ 
				clicked.prev().text(''); 
			} 
				}); 
			/*потеря фокуса полем*/ 
			$("div > input").blur( 
				function(e) 
				{ 
					var clicked = $(e.target), 
					clickedId = clicked.attr("id"); 
					if(clickedId=="siteLogin") 
					{ 
						if(clicked.val()=='') clicked.prev().text('Логин'); 
					} 
					else if(clickedId=="sitePass") 
					{ 
						if(clicked.val()=='') clicked.prev().text('Пароль');
					} 
				}); 
			});
	</script>

	<script>
			$('body').on('click', '.password-control', function () {
				if ($('#sitePass').attr('type') == 'password') {
					$(this).removeClass('fas fa-eye');
					$(this).addClass('view');
					$(this).addClass('fas fa-eye-slash');
					$('#sitePass').attr('type', 'text');
				} else {
					$(this).removeClass('view');
					$(this).removeClass('fas fa-eye-slash');
					$(this).addClass('fas fa-eye');
					$('#sitePass').attr('type', 'password');
				}
				return false;
			});
	</script>
}

</body>

Pages/Account/ResetPassword.cshtml
@page
@model Web2.Pages.ResetPasswordModel
@{
    ViewData["Title"] = "Сброс пароля";
}

<h2>@ViewData["Title"]</h2>
<h4>Введите пароль.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-page-handler="ResetPassword" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input name="code" asp-for="mod.Code" type="hidden"/>
            <div class="form-group">
                <label asp-for="mod.Email"></label>
                <input name="Email" asp-for="mod.Email" class="form-control" />
                <span asp-validation-for="mod.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label> Пароль </label>
                <input name="Password" asp-for="mod.Password" class="form-control" />
                <span asp-validation-for="mod.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
				<label> Повторите пароль </label>
                <input name="ConfirmPassword" asp-for="mod.ConfirmPassword" class="form-control" />
                <span asp-validation-for="mod.ConfirmPassword" class="text-danger"></span>
            </div>
            <button style="margin: 10px 0 0 0;" type="submit" class="btn btn-primary">Сбросить</button>
        </form>
    </div>
</div>

Pages/Account/ResetPasswordConfirmation.cshtml
@page
@model Web2.Pages.ResetPasswordConfirmationModel
@{
    ViewData["Title"] = "Подтверждение сброса пароля";
}

<h2>@ViewData["Title"]</h2>
<p>
    Ваш пароль сброшен. Для входа в приложение перейдите по <a href="/Account/Log">ссылке</a>.
</p>
