Models/Charts.cs
namespace Web2.Models
{
    // Подсчёт патологий.
    public class PathologCount
    {
        public string? Name { get; set; }
        public int Count { get; set; }
    }
    // Распределение показателей.
    public class Distribution
    {
        public string? Pocket { get; set; }
        public int Count { get; set; }
    }
}

Pages/Processing/Chart.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Web2.Data;
using Web2.Models;

namespace Web2.Pages
{
    public class ChartModel : PageModel
    {
        public int? G = 0;

        public int? B=1;
        public string NameA = "Кальций сыворотки крови (ммоль/л)";
        // выбор группы
        public List<SelectListItem>? GetGroup()
        {
            List<SelectListItem> group = new List<SelectListItem>();
            group.Add(new SelectListItem() { Text = "Контрольная группа", Value = "1" });
            group.Add(new SelectListItem() { Text = "Основная группа", Value = "2" });
            group.Add(new SelectListItem() { Text = "Группа сравнения", Value = "3" });
            return group;
        }
        // выбор показателя
        public List<SelectListItem>? GetAnalysis()
        {
            List<SelectListItem> analysis = new List<SelectListItem>();
            analysis.Add(new SelectListItem() { Text = "Кальций сыворотки крови (ммоль/л)", Value = "1" });
            analysis.Add(new SelectListItem() { Text = "Фосфор сыворотки крови (ммоль/л)", Value = "2" });
            analysis.Add(new SelectListItem() { Text = "Оксипролин сыворотки крови (ммоль/л)", Value = "3" });
            analysis.Add(new SelectListItem() { Text = "Экскреция кальция (мМ/сутки)", Value = "4" });
            analysis.Add(new SelectListItem() { Text = "Экскреция фосфора (ммоль/л)", Value = "5" });
            analysis.Add(new SelectListItem() { Text = "Экскреция оксипролина (мкм/мг креатинина)", Value = "6" });
            analysis.Add(new SelectListItem() { Text = "Степень выраженности ДСТ по Т.Милковской-Димитровой (в баллах)", Value = "7" });
            return analysis;
        }
        private readonly AppDbContext _context;

        public int[]? nums = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
        public string[] name = { "IzmenKontr", "KlinForm", "GrajaSmorl", "Osteoporoz", "UmenVisoti", "IzmenOpof", "Osteohondroz", "StabIzmen", "ENMG" };

        public List<double> data = new List<double>();
        public ChartModel(AppDbContext context)
        {
            _context = context;
        }

        public IList<Examination> examination { get; set; } = default!;
        public IList<Analyzes> analyzes { get; set; } = default!;
        // получение данных для графика : "кол-во патологий"
        public List<PathologCount> GetData1(int? G1)
        {
            List<PathologCount> pathologies = new List<PathologCount>();
            int[]? nums = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };

            int? group = G1;

            if (group == 0 || group == null)
                examination = _context.examination.FromSqlRaw($"SELECT * FROM examination ORDER BY id_examination").ToList();
            else
                examination = _context.examination.FromSqlRaw($"SELECT * FROM examination WHERE id_examination IN(SELECT id_examination FROM patient_examinations WHERE id_patient IN(SELECT id_patient FROM patient_archive WHERE id_patient IN(SELECT id_patient FROM archive_group WHERE id_group={group}) ORDER BY id_patient)) ORDER BY id_examination").ToList();

            foreach (var item in examination)
            {
                nums[0] += Convert.ToInt32(item.changing_the_contours_of_the_end_plates);
                nums[1] += Convert.ToInt32(item.wedgeshaped_vertebral_bodies);
                nums[2] += Convert.ToInt32(item.schmorl_hernia);
                nums[3] += Convert.ToInt32(item.osteoporosis_of_the_vertebrae);
                nums[4] += Convert.ToInt32(item.decrease_in_the_height_of_the_intervertebral_disc);
                nums[5] += Convert.ToInt32(item.change_in_the_contours_of_the_apophyses);
                nums[6] += Convert.ToInt32(item.signs_of_osteochondrosis);
                nums[7] += Convert.ToInt32(item.stabilographic_changes);
                nums[8] += Convert.ToInt32(item.enmg);
            }

            for (int i = 0; i < nums.Count(); i++)
            {
                pathologies.Add(new PathologCount()
                {
                    Name = name[i],
                    Count = nums[i]
                });
            }

            return pathologies;
        }
        // получение данных для графика: "Распределение показателей"
        public List<Distribution> GetData2(int? n, int? G1)
        {
            List<Distribution> distribution = new List<Distribution>();
            data.Clear();

            int? group = G1;

            if (group == 0 || group == null)
                analyzes = _context.analyzes.FromSqlRaw($"SELECT * FROM analyzes ORDER BY id_analysis").ToList();
            else
                analyzes = _context.analyzes.FromSqlRaw($"SELECT * FROM analyzes WHERE id_analysis IN(SELECT id_analysis FROM patient_analyzes WHERE id_patient IN(SELECT id_patient FROM patient_archive WHERE id_patient IN(SELECT id_patient FROM archive_group WHERE id_group={group}) ORDER BY id_patient)) ORDER BY id_analysis").ToList();

            foreach (var item in analyzes)
            {
                switch (n)
                {
                    case 1:
                        data.Add(item.serum_calcium);
                        break;
                    case 2:
                        data.Add(item.serum_phosphorus);
                        break;
                    case 3:
                        data.Add(item.serum_oxyproline);
                        break;
                    case 4:
                        data.Add(item.calcium_excretion);
                        break;
                    case 5:
                        data.Add(item.phosphorus_excretion);
                        break;
                    case 6:
                        data.Add(item.oxyproline_excretion);
                        break;
                    case 7:
                        data.Add(item.severity_of_dst);
                        break;
                }
            }

            if (data.Count > 0)
            {
                int pocket = (int)Math.Sqrt(data.Count());
                double min = data.Min();
                double max = data.Max();
                double sizeP = (max - min) / pocket;

                List<double> Pockets = new List<double>();
                Pockets.Add(min);
                for (int i = 0; i < pocket; i++)
                {
                    Pockets.Add(Pockets[i] + sizeP);
                }
                int[] dataP = new int[pocket + 1];
                Array.Clear(dataP, 0, dataP.Length);

                for (int i = 0; i < Pockets.Count - 1; i++)
                {
                    for (int j = 0; j < data.Count; j++)
                    {
                        if (data[j] >= Pockets[i] && data[j] <= Pockets[i + 1])
                            dataP[i]++;
                    }
                }

                for (int i = 0; i < dataP.Count(); i++)
                {
                    distribution.Add(new Distribution()
                    {
                        Pocket = Pockets[i].ToString("0.00"),
                        Count = dataP[i]
                    });
                }
            }

            return distribution;
        }

    }
}

Pages/Processing/Excel.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Drawing.Printing;
using Web2.Models;
using Microsoft.AspNetCore.Hosting;
using ExcelDataReader;
using System.Data;

namespace Web2.Pages
{
    public class ExcelModel : PageModel
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly Web2.Data.AppDbContext _context;
        [BindProperty]
        public List<List<string>> Data { get; set; }
        public ExcelModel(Web2.Data.AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            Data = new List<List<string>>();
            _webHostEnvironment = webHostEnvironment;
        }
        // модели для разных таблиц БД
        public patient_archive Patient { get; set; }
        public Analyzes AnalyzesP { get; set; }
        public Examination ExaminationP { get; set; }
        public Archive_Group Archive { get; set; }
        public Patient_Analyzes PA { get; set; }
        public Patient_Examination PE { get; set; }
        // выбор таблицы БД
        public List<SelectListItem>? GetName()
        {
            List<SelectListItem> group = new List<SelectListItem>();
            group.Add(new SelectListItem() { Text = "Архив пациентов", Value = "patient_archive" });
            group.Add(new SelectListItem() { Text = "Анализы", Value = "analyzes" });
            group.Add(new SelectListItem() { Text = "Результаты диспансеризации", Value = "examination" });
            group.Add(new SelectListItem() { Text = "Связь: пациенты-группы", Value = "archive_group" });
            group.Add(new SelectListItem() { Text = "Связь: пациенты-анализы", Value = "patient_analyzes" });
            group.Add(new SelectListItem() { Text = "Связь: пациенты-диспансеризация", Value = "patient_examinations" });
            return group;
        }
        public void OnGet(){}
        // ввод данных из Excel файла в БД
        public async Task<IActionResult> OnPostAdd(string table_name)
        {
            try
            {
                switch (table_name)
                {
                    case "patient_archive":
                        if (Data.Count == 6) {
                            for (int i = 0; i < Data[0].Count; i++)
                            {
                                Patient = new patient_archive();
                                Patient.name = Data[1][i];
                                Patient.surname = Data[2][i];
                                Patient.patronymic = Data[3][i];
                                var dateTime = DateTime.Parse(Data[4][i]);
                                Patient.birthday = DateOnly.FromDateTime(dateTime);
                                Patient.phone_num = Data[5][i];

                                _context.patient_archive.Add(Patient);
                                await _context.SaveChangesAsync();
                            }
                            break;
                        }
                        ModelState.AddModelError("", "Неверные данные");
                        break;
                    case "analyzes":
                        if (Data.Count == 8)
                        {
                            for (int i = 0; i < Data[0].Count; i++)
                            {
                                AnalyzesP = new Analyzes();
                                AnalyzesP.serum_calcium = Convert.ToDouble(Data[1][i]);
                                AnalyzesP.serum_phosphorus = Convert.ToDouble(Data[2][i]);
                                AnalyzesP.serum_oxyproline = Convert.ToDouble(Data[3][i]);
                                AnalyzesP.calcium_excretion = Convert.ToDouble(Data[4][i]);
                                AnalyzesP.phosphorus_excretion = Convert.ToDouble(Data[5][i]);
                                AnalyzesP.oxyproline_excretion = Convert.ToDouble(Data[6][i]);
                                AnalyzesP.severity_of_dst = Convert.ToInt32(Data[7][i]);

                                _context.analyzes.Add(AnalyzesP);
                                await _context.SaveChangesAsync();
                            }
                            break;
                        }
                        ModelState.AddModelError("", "Неверные данные");
                        break;
                    case "examination":
                        if (Data.Count == 13)
                        {
                            for (int i = 0; i < Data[0].Count; i++)
                            {
                                ExaminationP = new Examination();
                                var dateTime = DateTime.Parse(Data[1][i]);
                                ExaminationP.date = DateOnly.FromDateTime(dateTime);
                                ExaminationP.posture_holding_time = Convert.ToDouble(Data[2][i]);
                                ExaminationP.the_amount_of_kyphosis_in_degress = Convert.ToDouble(Data[3][i]);
                                ExaminationP.changing_the_contours_of_the_end_plates = Convert.ToBoolean(Data[4][i]);
                                ExaminationP.wedgeshaped_vertebral_bodies = Convert.ToBoolean(Data[5][i]);
                                ExaminationP.schmorl_hernia = Convert.ToBoolean(Data[6][i]);
                                ExaminationP.osteoporosis_of_the_vertebrae = Convert.ToBoolean(Data[7][i]);
                                ExaminationP.decrease_in_the_height_of_the_intervertebral_disc = Convert.ToBoolean(Data[8][i]);
                                ExaminationP.change_in_the_contours_of_the_apophyses = Convert.ToBoolean(Data[9][i]);
                                ExaminationP.signs_of_osteochondrosis = Convert.ToBoolean(Data[10][i]);
                                ExaminationP.stabilographic_changes = Convert.ToBoolean(Data[11][i]);
                                ExaminationP.enmg = Convert.ToBoolean(Data[12][i]);

                                _context.analyzes.Add(AnalyzesP);
                                await _context.SaveChangesAsync();
                            }
                            break;
                        }
                        ModelState.AddModelError("", "Неверные данные");
                        break;
                    case "archive_group":
                        if (Data.Count == 2)
                        {
                            for (int i = 0; i < Data[0].Count; i++)
                            {
                                Archive = new Archive_Group();
                                Archive.id_patient= Convert.ToInt32(Data[0][i]);
                                Archive.id_group= Convert.ToInt32(Data[1][i]);

                                _context.archive_group.Add(Archive);
                                await _context.SaveChangesAsync();
                            }
                            break;
                        }
                        ModelState.AddModelError("", "Неверные данные");
                        break;
                    case "patient_analyzes":
                        if (Data.Count == 2)
                        {
                            for (int i = 0; i < Data[0].Count; i++)
                            {
                                PA = new Patient_Analyzes();
                                PA.id_patient = Convert.ToInt32(Data[0][i]);
                                PA.id_analysis = Convert.ToInt32(Data[1][i]);

                                _context.patient_analyzes.Add(PA);
                                await _context.SaveChangesAsync();
                            }
                            break;
                        }
                        ModelState.AddModelError("", "Неверные данные");
                        break;
                    case "patient_examinations":
                        if (Data.Count == 2)
                        {
                            for (int i = 0; i < Data[0].Count; i++)
                            {
                                PE = new Patient_Examination();
                                PE.id_patient = Convert.ToInt32(Data[0][i]);
                                PE.id_examination = Convert.ToInt32(Data[1][i]);

                                _context.patient_examinations.Add(PE);
                                await _context.SaveChangesAsync();
                            }
                            break;
                        }
                        ModelState.AddModelError("", "Неверные данные");
                        break;
                }
            }
            catch (Exception ex)
            {
                return Redirect("/Error");
            }
            Data.Clear();
            return Page();
        }
        // подгрузка файла
        DataTableCollection ReadFromExcel(string filePath, ref List<string> sheetNames)
        {
            try
            {
                DataTableCollection tableCollection = null;

                using (var stream = System.IO.File.Open(filePath, FileMode.Open, FileAccess.Read))
                {
                    System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

                    using (IExcelDataReader reader = ExcelReaderFactory.CreateReader(stream))
                    {
                        DataSet result = reader.AsDataSet(new ExcelDataSetConfiguration()
                        {
                            ConfigureDataTable = (_) => new ExcelDataTableConfiguration() { UseHeaderRow = true }
                        });

                        tableCollection = result.Tables;

                        foreach (DataTable table in tableCollection)

Pages/Processing/DataPatient.cshtml
@page
@model Web2.Pages.DataPatientModel
@{
    ViewData["Title"] = "Данные для диагностики";
}

<div data-aos="fade-up-left" class="table-responsive">

<table id="tblCustomers" class="table table-hover">
    <thead>
        <tr class="table-secondary">
            <th class="noExl">Предсказание</th class="noExl">
            <th role="columnheader">
                Кальций сыворотки крови (ммоль/л)
            </th>
            <th role="columnheader">
                Фосфор сыворотки крови (ммоль/л)
            </th>
            <th role="columnheader">
                Оксипролин сыворотки крови (ммоль/л)
            </th>
            <th role="columnheader">
                Экскреция кальция (мМ/сутки)
            </th>
            <th role="columnheader">
                Экскреция фосфора (ммоль/л)
            </th>
            <th role="columnheader">
                Экскреция оксипролина (мкм/мг креатинина)
            </th>
            <th role="columnheader">
                Степень выраженности ДСТ по Т.Милковской-Димитровой (в баллах)
            </th>
             <th role="columnheader">
               Время удержания позы (мин.)
            </th>
            <th role="columnheader">
               Величина кифоза в градусах в грудном отделе позвоночника
            </th>
            <th role="columnheader">
               Наличие изменений стабилографических показателей
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.analyzes2) {
        <tr>
            <td class="noExl">
                <button class="fas fa-clinic-medical bt-ur" title="Предсказание" onclick="document.location='/Processing/Test?id_a=@item.id_analysis&id_e=@item.id_examination'"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.serum_calcium)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.serum_phosphorus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.serum_oxyproline)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.calcium_excretion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phosphorus_excretion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.oxyproline_excretion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.severity_of_dst)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.posture_holding_time)
             </td>
             <td>
                @Html.DisplayFor(modelItem => item.the_amount_of_kyphosis_in_degress)
             </td>
             <td>
                @Html.DisplayFor(modelItem => item.stabilographic_changes)
             </td>
        </tr>
}
    </tbody>
</table>
</div>

Pages/Processing/Excel.cshtml
@page
@model Web2.Pages.ExcelModel
@{
	ViewData["Title"] = "Excel";
}
@{
	if (ViewData["Message"] != null)
	{
		<div>
			@ViewData["Message"]
		</div>
	}
}

<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" />
</head>

<body>
    <div style="padding:30px;">

    <div class="all_windows" style="width: 600px;">
		<form asp-page-handler="Import" method="post" enctype="multipart/form-data">
            <i class="fas fa-file-excel" style="font-size: 36px; position: relative; top: 7px;"></i>
            <input class="g-button" type="file" name="file"/>
            <button class="c-button" type="submit">Загрузить</button>
		</form>
	</div>

    <div>
        <a class="bt-ur" href="~/Tools.rar" > Скачать инструмент для работы с базой данных </a>
    </div>

	<div class="table-responsive">
        <form asp-page-handler="Add" method="post">
            <p>
                <div class="row">
                    <div class="col-md-3">
                        <label class="form-label">Таблица</label>
                        <select class="form-select" name="table_name" asp-items="Model.GetName()">
                            <option value=""></option>
                        </select>
                    </div>
                </div>
            </p>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <table id="tblCustomers" class="table table-hover">
            <thead>
                <tr class="table-secondary">
                    @if (Model.Data.Count != 0)
                    {
                        @for (int k = 0; k < Model.Data[0].Count; k++)
                        {
                            <th role="columnheader">
                                @Html.DisplayFor(modelItem => @Model.Data[0][k])
                            </th>
                        }
                    }
                </tr>
            </thead>
            <tbody>
                
            @for (int i = 1; i < Model.Data.Count; i++)
            {
                <tr>
                    @for (int j = 0; j < Model.Data[i].Count; j++)
                    {
                        <td>
                            <input type="text" class="form-control" name="Data[@j]" asp-for="Data[i][j]" />
                        </td>
                    }
                </tr>
            }
			</tbody>
		</table>
			<input type="submit" class="c-button" value="Отправить" />
		</form>
    </div>
    </div>

    @section scripts{

        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>

        <script type="text/javascript">
            $(document).ready(function () {
                $('#tblCustomers').DataTable({
                    language: {
                        url: "https://cdn.datatables.net/plug-ins/1.13.4/i18n/ru.json",
                    },
                });
                $('.dataTables_length').addClass('bs-select');

            });
        </script>
    }
</body>

Pages/Processing/Test.cshtml
@page
@model Web2.Pages.TestModel
@{
    ViewData["Title"] = "Классификация";
}

<head>

    <link rel="stylesheet" href="~/css/pyscript.css" />

    <script defer src="~/scripts/pyscript.js" asp-append-version="true" ></script>

    <py-config>

        packages = ["numpy", "pandas", "scikit-learn", "lxml", "requests"]
        
        [splashscreen]
            enabled = false
        [[fetch]]
            from = "https://raw.githubusercontent.com/KenroyDytrim/PyScript/main/"
            files = ["model.py"]

    </py-config>

</head>

<body style="font-size: 16px;">

    <h1>Диагностика патологий</h1>

    <hr />

    <br>

    <div style="display:flex; justify-content: space-between;">

    <div style="margin: 0px 60px 0px 0px; font-size: 1.4vw; width: 45vw;">
    <h2 style="font-size: 2vw;">Данные пациента</h2>

        <p style="width: 45vw; display:flex; justify-content: space-between;">
        <label>Кальций сыворостки крови (ммоль/л)</label>
                <input id="an1" asp-for="Analyzes.serum_calcium" class="inputAn" min="0" max="30" step="0.1" type="number" style="width: 15vw; height: 2vw;" />
    </p>
        <p style="width: 45vw; display:flex; justify-content: space-between;">
        <label>Фосфор сыворотки крови (ммоль/л)</label>
                <input id="an2" asp-for="Analyzes.serum_phosphorus" class="inputAn" min="0" max="30" step="0.1" type="number" style="width: 15vw; height: 2vw;" />
    </p>
        <p style="width: 45vw; display:flex; justify-content: space-between;">
        <label>Оксипролин сыворотки крови (мкмоль/л)</label>
                <input id="an3" asp-for="Analyzes.serum_oxyproline" class="inputAn" min="0" max="30" step="0.1" type="number" style="width: 15vw; height: 2vw;" />
    </p>
        <p style="width: 45vw; display:flex; justify-content: space-between;">
        <label>Эксреция кальция (мМ/сутки)</label>
                <input id="an4" asp-for="Analyzes.calcium_excretion" class="inputAn" min="0" max="30" step="0.1" type="number" style="width: 15vw; height: 2vw;" />
    </p>
        <p style="width: 45vw; display:flex; justify-content: space-between;">
        <label>Экскреция фосфора (ммоль/л)</label>
                <input id="an5" asp-for="Analyzes.phosphorus_excretion" class="inputAn" min="0" max="30" step="0.1" type="number" style="width: 15vw; height: 2vw;" />
    </p>
        <p style="width: 45vw; display:flex; justify-content: space-between;">
        <label>Экскреция оксипролина (мкм/мг креатина)</label>
                <input id="an6" asp-for="Analyzes.oxyproline_excretion" class="inputAn" min="0" max="30" step="0.1" type="number" style="width: 15vw; height: 2vw;" />
    </p>
        <p style="width: 45vw; display:flex; justify-content: space-between;">
        <label>Степень выраженности ДСТ (в баллах)</label>
                <input id="an7" asp-for="Analyzes.severity_of_dst" class="inputAn" min="0" max="90" step="1" type="number" style="width: 15vw; height: 2vw;" />
    </p>
        <p style="width: 45vw; display:flex; justify-content: space-between;">
        <label>Время удержания позы</label>
                <input id="an8" asp-for="Examination.posture_holding_time" class="inputAn" min="0" max="20" step="0.1" type="number" style="width: 15vw; height: 2vw;" />
    </p>
        <p style="width: 45vw; display:flex; justify-content: space-between;">
        <label>Величина кифоза в градусах</label>
                <input id="an9" asp-for="Examination.the_amount_of_kyphosis_in_degress" class="inputAn" min="0" max="120" step="1" type="number" style="width: 15vw; height: 2vw;" />
    </p>

        <p style="width: 45vw; display:flex; justify-content: space-between;">
        <label>Наличие изменений стабилографических показателей</label>
                <input id="an10" type="checkbox" asp-for="Examination.stabilographic_changes" style="width: 1.6vw; height: 1.6vw;"/>
    </p>

    </div>

    <div style="display:flex; flex-direction:column; font-size:1.2vw; width:40vw;">
        <h2 style="font-size: 2vw;">Выберите патологии для прогноза:</h2>

        <p style="display:flex;">
            <input name="ch1" id="ch1" type="checkbox" value="0" style="width: 1.6vw; height: 1.6vw;" />
            <label>Изменение контуров замыкательных пластинок</label>
        </p>

        <p>
            <input name="ch2" id="ch2" type="checkbox" value="1" style="width: 1.6vw; height: 1.6vw;" />
            <label>Клиновидная форма тел позвонков</label>
        </p>

        <p>
            <input name="ch3" id="ch3" type="checkbox" value="2" style="width: 1.6vw; height: 1.6vw;" />
            <label>Грыжи Шморля</label>
        </p>

        <p>
            <input name="ch4" id="ch4" type="checkbox" value="3" style="width: 1.6vw; height: 1.6vw;" />
            <label>Остеопороз тел позвонков</label>
        </p>

        <p>
            <input name="ch5" id="ch5" type="checkbox" value="4" style="width: 1.6vw; height: 1.6vw;" />
            <label>Уменьшение высоты межпозвонкового диска</label>
        </p>

        <p>
            <input name="ch6" id="ch6" type="checkbox" value="5" style="width: 1.6vw; height: 1.6vw;" />
            <label>Изменение контуров апофизов</label>
        </p>

        <p>
            <input name="ch7" id="ch7" type="checkbox" value="6" style="width: 1.6vw; height: 1.6vw;" />
            <label>Признаки остеохондроза</label>
        </p>

        <p>
            <input name="ch8" id="ch8" type="checkbox" value="7" style="width: 1.6vw; height: 1.6vw;" />
            <label>ЭНМГ (болезни двигательных нейронов)</label>
        </p>

	</div>

    </div>

    <button id="run" type="button" class="c-button" py-click="analysis()">Анализ</button>

    <div style="display:flex;">

    <p style="font-size: 24px;">Результат: 🐍</p>

    <a href="/Instructions" class="link"><span> ? </span></a>

    </div>

	<div style="width: 45vw; display:none; " id='err'>
        <p style="color: red; font-size: 2.5vw; " > Все поля должны быть заполнены!!! </p>
	</div>

    <div data-aos="fade-up-left" id="main" style="display: none;">

    <div class="blP">
        <div class="blR">
            <p style="display:none" id='r1_1'></p>
            <p style="display:none" id='r1_2'></p>
            <p style="display:none" id='r1_3'></p>
            <p style="display:none" id='r1_4'></p>
            <p style="display:none" id='r1_5'></p>
            <p style="display:none" id='r1_6'></p>
            <p style="display:none" id='r1_7'></p>
            <p style="display:none" id='r1_8'></p>
        </div>
    </div>

    <div class="blP" style=" align-items: center; flex-direction: column;">
        <p> 0 - низкая вероятность патологии </p>
        <p> 1 - требуется обратить внимание </p>
    </div>

    </div>

    <py-script src="https://raw.githubusercontent.com/KenroyDytrim/PyScript/main/model.py"> </py-script>

    <div id="load-scr" class="loader2">
        <div id="page-loader" class="loader">
            <div class="inner one"></div>
            <div class="inner two"></div>
            <div class="inner three"></div>
        </div>
    </div>

	@section scripts{
		<script src="~/scripts/loading.js" asp-append-version="true" ></script>
    }

</body>